# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8f35d06a8a7e7d2273e5eadabd81cd327591c6321435d8fe347d1f25bf14fc0f89851b0b5d6b121d84f5ba98112ac32dc487eeb0a9912cdc90303e73d5089e5

test:
  secret_key_base: 8e338647eba85f4160af5c8d159b257481e9c6819c623044dccdce9562720b25f1721b3a044cb6bd1f2f762eba033358079e47e81c969d075c6ae9277611c0aa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
